In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

%matplotlib inline

In [2]:
# Constants

num_inputs = 2
num_neurons = 3

In [3]:
# Placeholders

x0 = tf.placeholder(tf.float32, shape=[None, num_inputs])
x1 = tf.placeholder(tf.float32, shape=[None, num_inputs])

In [4]:
# Variables

Wx = tf.Variable(tf.random_normal([num_inputs, num_neurons]))
Wy = tf.Variable(tf.random_normal([num_neurons, num_neurons]))

b = tf.Variable(tf.zeros([1, num_neurons]))

In [5]:
# Graph

In [6]:
y0 = tf.tanh(tf.matmul(x0, Wx) + b)

In [7]:
y1 = tf.tanh(tf.matmul(y0, Wy) + tf.matmul(x1, Wx) + b)

In [8]:
init = tf.global_variables_initializer()

In [9]:
# Create data

In [10]:
# Timestamp 0
x0_batch = np.array([
    [0, 1], [2, 3], [4, 5]
])

# Timestamp 1
x1_batch = np.array([
    [100, 101], [102, 103], [104, 105]
])

In [11]:
with tf.Session() as sess:
    sess.run(init)
    
    y0_output_vals, y1_output_vals = sess.run(
        [y0, y1],
        feed_dict={x0: x0_batch, x1: x1_batch}
    )

    print(y0_output_vals)
    print(y1_output_vals)

[[ 0.46649832  0.97503     0.14218476]
 [ 0.9302284   0.999995   -0.5122832 ]
 [ 0.9928425   1.         -0.8550921 ]]
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
